// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMih_d6JwVRCNz8qo8yxhzH6JynwsVLmU',
    appId: '1:949364734579:web:2bf387fe7578f1e1628806',
    messagingSenderId: '949364734579',
    projectId: 'gymmanagement-app',
    authDomain: 'gymmanagement-app.firebaseapp.com',
    storageBucket: 'gymmanagement-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIgA9pGdjM3xtJYUg1FJEr0tQqdPFZKoY',
    appId: '1:949364734579:android:4ed4029504d82503628806',
    messagingSenderId: '949364734579',
    projectId: 'gymmanagement-app',
    storageBucket: 'gymmanagement-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApPnvde72mmp92h6jTXxRHPZ47Owwq2ZY',
    appId: '1:949364734579:ios:b78ee29ed6247032628806',
    messagingSenderId: '949364734579',
    projectId: 'gymmanagement-app',
    storageBucket: 'gymmanagement-app.firebasestorage.app',
    iosBundleId: 'com.example.gymmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApPnvde72mmp92h6jTXxRHPZ47Owwq2ZY',
    appId: '1:949364734579:ios:b78ee29ed6247032628806',
    messagingSenderId: '949364734579',
    projectId: 'gymmanagement-app',
    storageBucket: 'gymmanagement-app.firebasestorage.app',
    iosBundleId: 'com.example.gymmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMih_d6JwVRCNz8qo8yxhzH6JynwsVLmU',
    appId: '1:949364734579:web:3636b1bc7aae8b0f628806',
    messagingSenderId: '949364734579',
    projectId: 'gymmanagement-app',
    authDomain: 'gymmanagement-app.firebaseapp.com',
    storageBucket: 'gymmanagement-app.firebasestorage.app',
  );
}
